import { useState } from 'react';

const apiBase = import.meta.env.VITE_API_BASE_URL || '';

async function parseJsonResponse(response) {
  const text = await response.text();
  if (!text) {
    return {};
  }
  return JSON.parse(text);
}

export default function UploadPanel({ onJobCreated }) {
  const [file, setFile] = useState(null);
  const [submitting, setSubmitting] = useState(false);
  const [message, setMessage] = useState('');
  const [messageType, setMessageType] = useState('');

  const handleSubmit = async (event) => {
    event.preventDefault();
    if (!file) {
      setMessage('Choose an .xlsx file generated by PDIE first.');
      setMessageType('error');
      return;
    }

    setSubmitting(true);
    setMessage('');
    setMessageType('');

    try {
      const formData = new FormData();
      formData.append('file', file);

      const response = await fetch(`${apiBase}/api/uploads`, {
        method: 'POST',
        body: formData
      });

      const data = await parseJsonResponse(response);
      if (!response.ok) {
        throw new Error(data.error || 'Upload failed');
      }

      onJobCreated(data.jobId);
      setMessage(`Upload accepted. Job ${data.jobId} is now queued.`);
      setMessageType('success');
    } catch (uploadError) {
      setMessage(uploadError.message);
      setMessageType('error');
    } finally {
      setSubmitting(false);
    }
  };

  return (
    <section className="panel">
      <div className="panel-header">
        <div>
          <p className="eyebrow">Step 2</p>
          <h2>Upload Workbook</h2>
        </div>
      </div>

      <p className="panel-copy">
        Upload a completed template workbook. The API returns a job id immediately and all progress
        is exposed over polling endpoints.
      </p>

      {message ? <div className={`message ${messageType}`}>{message}</div> : null}

      <form className="stack" onSubmit={handleSubmit}>
        <label className="file-picker">
          <span>{file ? file.name : 'Choose .xlsx workbook'}</span>
          <input
            type="file"
            accept=".xlsx"
            onChange={(event) => setFile(event.target.files?.[0] || null)}
          />
        </label>

        <button className="primary-button" type="submit" disabled={!file || submitting}>
          {submitting ? 'Uploading...' : 'Upload Workbook'}
        </button>
      </form>
    </section>
  );
}
